version: '3.8'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:1234" # Change this per app
    volumes:
      - settings_data:/app/settings
    environment:
      - FLASK_ENV=production
    env_file:
      - .env
    networks:
      - default


#Set Volume here, this is for settings
volumes:
  settings_data: